---
- name: create service for deployment
  hosts: kubernetes

  tasks:
  - name: Copy manifest file
    copy:
      src: "{{ item }}"
      dest: /home/ubuntu/k8s/
      owner: ubuntu
      group: ubuntu
      mode: 0750
    with_items:
      - k8s-service.yml

  - name: create a service
    command: kubectl apply -f /home/ubuntu/k8s/k8s-service.yml

